### ISSUE TITLE
can't connect to ui after updateing js-controller and admin 

### ISSUE THREAD

**Issue by Presl1983** [MaxWinterstein/homeassistant-addons#184]
can't connect to ui after updateing js-controller and admin.

anyone else got that issue?

**Comment by jnsness** [comment]
Jip - same problem here. Don't know what changed. Just got

> Error: Cannot find module '/data/iobroker/node_modules/iobroker.js-controller/controller.js'

**Comment by bastard-GIT** [comment]
Same here:

```

------------------------------------------------------------
---------------     2023-09-21 21:03:46      ---------------
------------------------------------------------------------
 
------------------------------------------------------------
-----       Welcome to your ioBroker-container!        -----
-----          Startupscript is now running.           -----
-----                Please be patient!                -----
------------------------------------------------------------
 
------------------------------------------------------------
-----              Debugging information               -----
-----                                                  -----
-----                      System                      -----
-----               arch:      aarch64                 -----
-----                                                  -----
-----                     Versions                     -----
-----               image:                             -----
-----               node:      v12.21.0                -----
-----               npm:       6.14.11                 -----
-----                                                  -----
-----                       ENV                        -----
-----               SETGID:    1000                    -----
-----               SETUID:    1000                    -----
------------------------------------------------------------
 
------------------------------------------------------------
-----         Step 1 of 5: Preparing container         -----
------------------------------------------------------------
 
Registering maintenance script as command.
Done.
 
------------------------------------------------------------
-----   Step 2 of 5: Detecting ioBroker installation   -----
------------------------------------------------------------
 
Existing installation of ioBroker detected in /opt/iobroker.
 
------------------------------------------------------------
-----   Step 3 of 5: Checking ioBroker installation    -----
------------------------------------------------------------
 
(Re)Setting folder permissions (This might take a while! Please be patient!)...
Done.
 
Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
Done.
 
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
/opt/scripts/iobroker_startup.sh: line 205: [: !=: unary operator expected
------------------------------------------------------------
-----      Step 4 of 5: Applying special settings      -----
------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information take a look at readme.md on Github!
 
------------------------------------------------------------
-----          Step 5 of 5: ioBroker startup           -----
------------------------------------------------------------
 
Starting ioBroker...
 
Running 'eval' commands
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module '/data/iobroker/node_modules/iobroker.js-controller/controller.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by Dr4g0nM4st3r** [comment]
same problem here, Problem accures since reboot (and eval iobroker update && iobroker upgrade self)

**Comment by Hakko62** [comment]
… same issue here. After System reboot the Addon doesn‘t start.

**Comment by jove01** [comment]
Some problem here after changing my ha-hardware and reinstall this addon. The Status of the addon ist green, but the same Error and the website can't connect.

**Comment by jove01** [comment]
Hello
I tried it without 
`eval: iobroker update && iobroker upgrade self`
that works, but I need the update for installing "mqtt.client"!

With the eval-option the error occus:

`Adapter    "zwave2"        : 3.1.0    
Update js-controller from @3.2.16 to @5.0.16
NPM version: 6.14.11
npm install iobroker.js-controller@5.0.16 --loglevel error --unsafe-perm --prefix "/data/iobroker" (System call)
In file included from ../node_modules/nan/nan.h:62,
                 from ../src/main.cpp:3:
/opt/iobroker/.cache/node-gyp/12.21.0/include/node/node.h:737:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/opt/iobroker/.cache/node-gyp/12.21.0/include/node/node.h:771:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/main.cpp:42:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(diskusage, Init)
 ^~~~~~~~~~~
In file included from ../node_modules/nan/nan.h:62,
                 from ../src/unix_dgram.cc:5:
/opt/iobroker/.cache/node-gyp/12.21.0/include/node/node.h:737:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/opt/iobroker/.cache/node-gyp/12.21.0/include/node/node.h:771:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/unix_dgram.cc:404:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(unix_dgram, Initialize)
 ^~~~~~~~~~~
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:timers/promises'
Require stack:
- /data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/dbConnection.js
- /data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup.js
- /data/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js
- /data/iobroker/node_modules/iobroker.js-controller/iobroker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/dbConnection.js:34:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/dbConnection.js',
    '/data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup.js',
    '/data/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js',
    '/data/iobroker/node_modules/iobroker.js-controller/iobroker.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.js-controller@5.0.16 install: `node iobroker.js setup first`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iobroker.js-controller@5.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/iobroker/.npm/_logs/2023-11-30T12_03_41_153Z-debug.log
host.f1c878cb-iobroker Cannot install iobroker.js-controller@5.0.16: 1
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/data/iobroker/node_modules/iobroker.js-controller/controller.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

Please help; thanks

**Comment by MaxWinterstein** [comment]
this add-on needs a huge makeover... 

i will try to put it somewhere in my schedule, as it seems like there is some interest in it :)

**Comment by jove01** [comment]
> this add-on needs a huge makeover...
> 
> i will try to put it somewhere in my schedule, as it seems like there is some interest in it :)

Thanks you for the Informationen. I hope so

**Comment by jnsness** [comment]
It definitely is :-)

**Comment by td-mygit** [comment]
Are there any news about this? I also need to upgrade the js-controller because I would like to use the MQTT client.

**Comment by SolarPower2024** [comment]
Need to bring this issue up again.

@MaxWinterstein any chance that this can be fixed? As the others I would need to use the mqtt client to bring data to my home assistant instance, for which an update is unfortunately needed.

**Comment by MaxWinterstein** [comment]
Closing as the ioBroker add-on has been deprecated — I no longer have the time or personal interest to maintain it. No further bug fixes or updates will be provided. Thanks for reporting!
