### ISSUE TITLE
Error after upgrade to 1.0.0

### ISSUE THREAD

**Issue by ronaldt80** [MaxWinterstein/homeassistant-addons#3]
Hi Max, thanks for all the efforts. I just upgraded to the new version and this resulted in the below errors. Any thoughts as to what may cause this? The log file mentioned is not in my smb share. Where can I find it?

cheers,
Ronald

ps. I reverted to 0.7.0, everything works.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.1.1
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:31:46] INFO: Exporting log level for nodejs: info
[16:31:46] INFO: Symlinking data dir
[16:31:46] INFO: Generating config.yml from options.json
[16:31:47] INFO: Image build with version 0.2.0
[16:31:47] INFO: starting original stuff...

> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js

info: Migrating the database... {"timestamp":"2021-01-10T15:31:49.301Z"}
info: Stored device: Backyard ([xxxx] - type: T8113) {"timestamp":"2021-01-10T15:31:52.283Z"}
info: Stored device: Front yard ([xxxx]- type: T8113) {"timestamp":"2021-01-10T15:31:52.286Z"}
info: Stored device: Doorbell ([xxxx]- type: T8210) {"timestamp":"2021-01-10T15:31:52.288Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-01-10T15:31:52.339Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-01-10T15:31:52.591Z"}
(node:355) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at MqttClient.processPushNotification (/app/mqtt/client.js:92:72)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:355) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at MqttClient.processPushNotification (/app/mqtt/client.js:92:72)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-10T15_31_53_113Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by MaxWinterstein** [comment]
As far as I can tell this is not really based on the addon, as it seems to happen to non-addon users as well, see

https://github.com/matijse/eufy-ha-mqtt-bridge/issues/32

I think we should follow the issue there, as it is in the repo of the real maintainer.

/close

**Comment by MaxWinterstein** [comment]
Should be fixed with bridge v.0.2.1

Addon is updated as well to Version `0.2.1`
